# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: 定期実行してQiitaのスクショを更新する

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron:  '0 6,10,13,23 * * *' # 毎日UTCの6:00, 10:00, 13:00, 23:00に実行。日本時間15:00, 19:00, 22:00, 8:00に当たる

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        version: [1]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
        - uses: actions/checkout@v3

        - name: Setup Bun
          uses: oven-sh/setup-bun@v1
          with:
            bun-version: 1.0.11 # or "latest", "canary", <sha>
        
        - name: Install Japanese fonts
          run: sudo apt-get install -y fonts-sawarabi-gothic

        - name: Install bun puppeteer
          run: npx puppeteer browsers install chrome

        - name: Install dependencies
          run: bun install
        
        - name: 実行
          run: > 
            DISCORD_WEBHOOK_URL=${{secrets.DISCORD_WEBHOOK_URL}}
            bun run start

        # - name: Log action...
        #   run: > 
        #   npm run log
        
        - name: git commit & push
          run: |
            git config core.filemode false
            if ! git diff --exit-code --quiet
            then
                git add --update
                git config user.name github-actions
                git config user.email action@github.com
                git commit -m "Commit by github-actions"
                git push https://${{github.actor}}:${{secrets.GITHUB_TOKEN}}@github.com/${{github.repository}}.git HEAD:${{github.ref}}
            fi

        # # キャッシュ
        # - name: Cache dependencies
        #   uses: actions/cache@v3
        #   with:
        #     path: ~/.npm
        #     key: npm-${{ hashFiles('package-lock.json') }} 
        #     restore-keys: npm-
